version: "3.6"
services:
  test:
    container_name: test
    image: index.docker.io/eclipse77/test
    command: python app.py
    volumes:
      - ./instance:/app/instance
    networks:
      - main
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope test
networks:
  main:
    driver: bridge